#!/usr/bin/env python
"""
daily_price_snapshot.py — 获取当日价格快照并生成买方日报数据

使用方法：
    python daily_price_snapshot.py --use-search  # 使用 web_search
    python daily_price_snapshot.py               # 使用缓存/预设数据
"""
import json
import argparse
from pathlib import Path
from datetime import datetime

WATCHLIST_PATH = Path("11.投资机会跟踪报告/ideas_watchlist.json")
OUTPUT_PATH = Path("11.投资机会跟踪报告/daily_reports")

def load_watchlist():
    with open(WATCHLIST_PATH, "r", encoding="utf-8") as f:
        return json.load(f)

def get_prices_from_search() -> dict:
    """
    使用 web_search 获取价格数据
    注意：这需要在支持 web_search 的环境中运行
    """
    # 这里调用 web_search 工具
    # 在实际环境中，这会被替换为真实的 API 调用
    from web_search_tool import web_search
    
    tickers = ["GOOGL", "NVDA", "MU", "TSM", "UBER", "META", "AMZN", "NET"]
    results = {}
    
    for ticker in tickers:
        try:
            search_result = web_search(f"{ticker} stock price today February 2026", provider="dashscope")
            results[ticker] = {
                "search_results": search_result,
                "fetched_at": datetime.now().isoformat()
            }
        except Exception as e:
            results[ticker] = {"error": str(e)}
    
    return results

def get_prices_manual() -> dict:
    """
    手动输入的价格数据（从 web_search 获取后填写）
    """
    return {
        "GOOGL": {
            "price": 312.90,
            "change_pct": 3.5,
            "source": "Morningstar",
            "date": "2026-02-25"
        },
        "NVDA": {
            "price": 184.72,
            "change_pct": -5.5,
            "source": "Yahoo Finance",
            "date": "2026-02-26"
        },
        "MU": {"price": None, "change_pct": None, "source": "待更新", "date": "2026-02-27"},
        "TSM": {"price": None, "change_pct": None, "source": "待更新", "date": "2026-02-27"},
        "UBER": {"price": None, "change_pct": None, "source": "待更新", "date": "2026-02-27"},
        "META": {"price": None, "change_pct": None, "source": "待更新", "date": "2026-02-27"},
        "AMZN": {"price": None, "change_pct": None, "source": "待更新", "date": "2026-02-27"},
        "NET": {"price": None, "change_pct": None, "source": "待更新", "date": "2026-02-27"},
    }

def generate_price_report(prices: dict) -> str:
    """生成价格报告 Markdown"""
    lines = [
        "# 价格快照报告",
        f"> 生成时间：{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "## 美股持仓价格",
        "",
        "| 标的 | 价格 | 涨跌 | 来源 | 日期 |",
        "|---|---|---|---|---|"
    ]
    
    for symbol, data in prices.items():
        price = f"${data['price']}" if data.get('price') else "N/A"
        change = f"{data['change_pct']:+.1f}%" if data.get('change_pct') else "N/A"
        source = data.get('source', 'N/A')
        date = data.get('date', 'N/A')
        lines.append(f"| {symbol} | {price} | {change} | {source} | {date} |")
    
    lines.extend([
        "",
        "## 使用说明",
        "",
        "1. 此报告供买方日报引用价格数据",
        "2. 优先使用 dashscope web_search 获取最新价格",
        "3. 如遇限流，使用缓存/手动更新数据",
        "",
        "---",
        "*Generated by daily_price_snapshot.py*"
    ])
    
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser(description="获取持仓价格快照")
    parser.add_argument("--use-search", action="store_true", help="使用 web_search 获取实时数据")
    parser.add_argument("--output", type=str, help="输出文件路径")
    args = parser.parse_args()
    
    wl = load_watchlist()
    
    if args.use_search:
        print("使用 web_search 获取价格数据...")
        # prices = get_prices_from_search()
        print("注意：web_search 需要在支持的环境中运行")
        print("当前使用预设数据...")
        prices = get_prices_manual()
    else:
        print("使用预设/缓存数据...")
        prices = get_prices_manual()
    
    # 生成报告
    report = generate_price_report(prices)
    
    # 保存
    if args.output:
        output_path = Path(args.output)
    else:
        output_path = OUTPUT_PATH / f"price_snapshot_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report)
    
    print(f"价格报告已保存至：{output_path}")
    
    # 同时保存 JSON
    json_path = output_path.with_suffix(".json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(prices, f, ensure_ascii=False, indent=2)
    
    print(f"价格数据已保存至：{json_path}")

if __name__ == "__main__":
    main()
